# creates 'annar' user and copies key to ~/.ssh/authorized_hosts
---
- name: add user
  user:
    name: admin
    state: present
    password_lock: yes
    comment: ''
    shell: /bin/bash

- name: create .ssh directory
  file:
    path: /home/annar/.ssh
    owner: annar
    group: annar
    mode: '0700'
    state: directory

- name: copy ssh key
  copy:
    src: ../keys/admin_id_ed25519.pub
    dest: /home/admin/.ssh/authorized_keys
    owner: annar
    group: annar
    mode: '0644'

- name: add to sudoers
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%admin .*'
    line: '%admin   ALL=(ALL:ALL)   NOPASSWD:ALL'
    validate: /usr/sbin/visudo -cf %s
