# creates 'admin' user and copies key to ~/.ssh/authorized_hosts
---
- name: add user
  user:
    name: superpi
    state: present
    password_lock: yes
    comment: ''
    shell: /bin/bash

- name: create .ssh directory
  file:
    path: /home/superpi/.ssh
    owner: superpi
    group: superpi
    mode: '0700'
    state: directory

- name: copy ssh key
  copy:
    src: ../keys/superpi_id_ed25519.pub
    dest: /home/superpi/.ssh/authorized_keys
    owner: superpi
    group: superpi
    mode: '0644'

- name: add to sudoers
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%admin .*'
    line: '%superpi   ALL=(ALL:ALL)   NOPASSWD:ALL'
    validate: /usr/sbin/visudo -cf %s
