---
- name: update apt cache and perform a 'dist-upgrade'
  apt:
    update_cache: yes
    upgrade: dist
    force_apt_get: yes

- name: is a reboot required?
  stat:
    path: /var/run/reboot-required
    get_md5: no
  register: reboot_required_file

- name: reboot is necessary
  reboot:
    msg: "the system is going down"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
  register: reboot_was_necessary
  when: reboot_required_file.stat.exists

- name: update apt cache and perform a 'dist-upgrade'
  apt:
    update_cache: yes
    upgrade: dist
    force_apt_get: yes
  when: reboot_was_necessary.changed

- name: clean up
  apt:
    autoclean: yes

- name: remove unused packages
  apt:
    autoremove: yes
    purge: yes
